create sequence "public"."projects_id_seq";


  create table "public"."analytics_logs" (
    "id" bigint generated by default as identity not null,
    "region" text,
    "latency" bigint,
    "created_at" timestamp with time zone not null default now(),
    "project_id" integer
      );


alter table "public"."analytics_logs" enable row level security;


  create table "public"."projects" (
    "id" integer not null default nextval('public.projects_id_seq'::regclass),
    "name" text not null,
    "api_key" text not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."projects" enable row level security;

alter sequence "public"."projects_id_seq" owned by "public"."projects"."id";

CREATE UNIQUE INDEX analytics_logs_pkey ON public.analytics_logs USING btree (id);

CREATE UNIQUE INDEX projects_api_key_key ON public.projects USING btree (api_key);

CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);

alter table "public"."analytics_logs" add constraint "analytics_logs_pkey" PRIMARY KEY using index "analytics_logs_pkey";

alter table "public"."projects" add constraint "projects_pkey" PRIMARY KEY using index "projects_pkey";

alter table "public"."analytics_logs" add constraint "analytics_logs_project_id_fkey" FOREIGN KEY (project_id) REFERENCES public.projects(id) not valid;

alter table "public"."analytics_logs" validate constraint "analytics_logs_project_id_fkey";

alter table "public"."projects" add constraint "projects_api_key_key" UNIQUE using index "projects_api_key_key";

create or replace view "public"."project_performance_summary" as  SELECT p.name AS project_name,
    count(l.id) AS total_requests,
    round(avg(l.latency), 2) AS avg_latency,
    max(l.latency) AS max_latency
   FROM (public.projects p
     LEFT JOIN public.analytics_logs l ON ((p.id = l.project_id)))
  GROUP BY p.id, p.name;


grant delete on table "public"."analytics_logs" to "anon";

grant insert on table "public"."analytics_logs" to "anon";

grant references on table "public"."analytics_logs" to "anon";

grant select on table "public"."analytics_logs" to "anon";

grant trigger on table "public"."analytics_logs" to "anon";

grant truncate on table "public"."analytics_logs" to "anon";

grant update on table "public"."analytics_logs" to "anon";

grant delete on table "public"."analytics_logs" to "authenticated";

grant insert on table "public"."analytics_logs" to "authenticated";

grant references on table "public"."analytics_logs" to "authenticated";

grant select on table "public"."analytics_logs" to "authenticated";

grant trigger on table "public"."analytics_logs" to "authenticated";

grant truncate on table "public"."analytics_logs" to "authenticated";

grant update on table "public"."analytics_logs" to "authenticated";

grant delete on table "public"."analytics_logs" to "postgres";

grant insert on table "public"."analytics_logs" to "postgres";

grant references on table "public"."analytics_logs" to "postgres";

grant select on table "public"."analytics_logs" to "postgres";

grant trigger on table "public"."analytics_logs" to "postgres";

grant truncate on table "public"."analytics_logs" to "postgres";

grant update on table "public"."analytics_logs" to "postgres";

grant delete on table "public"."analytics_logs" to "service_role";

grant insert on table "public"."analytics_logs" to "service_role";

grant references on table "public"."analytics_logs" to "service_role";

grant select on table "public"."analytics_logs" to "service_role";

grant trigger on table "public"."analytics_logs" to "service_role";

grant truncate on table "public"."analytics_logs" to "service_role";

grant update on table "public"."analytics_logs" to "service_role";

grant delete on table "public"."projects" to "anon";

grant insert on table "public"."projects" to "anon";

grant references on table "public"."projects" to "anon";

grant select on table "public"."projects" to "anon";

grant trigger on table "public"."projects" to "anon";

grant truncate on table "public"."projects" to "anon";

grant update on table "public"."projects" to "anon";

grant delete on table "public"."projects" to "authenticated";

grant insert on table "public"."projects" to "authenticated";

grant references on table "public"."projects" to "authenticated";

grant select on table "public"."projects" to "authenticated";

grant trigger on table "public"."projects" to "authenticated";

grant truncate on table "public"."projects" to "authenticated";

grant update on table "public"."projects" to "authenticated";

grant delete on table "public"."projects" to "postgres";

grant insert on table "public"."projects" to "postgres";

grant references on table "public"."projects" to "postgres";

grant select on table "public"."projects" to "postgres";

grant trigger on table "public"."projects" to "postgres";

grant truncate on table "public"."projects" to "postgres";

grant update on table "public"."projects" to "postgres";

grant delete on table "public"."projects" to "service_role";

grant insert on table "public"."projects" to "service_role";

grant references on table "public"."projects" to "service_role";

grant select on table "public"."projects" to "service_role";

grant trigger on table "public"."projects" to "service_role";

grant truncate on table "public"."projects" to "service_role";

grant update on table "public"."projects" to "service_role";


  create policy "Enable all access"
  on "public"."analytics_logs"
  as permissive
  for all
  to public
using (true);



  create policy "Enable all access"
  on "public"."projects"
  as permissive
  for all
  to public
using (true);




